version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: An1M3ArCAd3
    ports:
      - "5432:5432"
    volumes:
      - ./pgData:/var/lib/postgresql/data

volumes:
  pgData: