version: '3.8'
services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: An1M3ArCaD3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

